background {
    monitor =
    path = /home/lenz/Pictures/Wallpapers/wp1.png
    blur_passes = 2
    blur_size = 6
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 80
    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    position = 0, -80
    halign = center
    valign = center
}